name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NodeRed version number'
        required: true
        default: 'vx.x.x'

env:
  REGISTRY: mrmadalex/my_new_nodered
  BUILD_NUMBER_OFFSET: 55


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate build number
        id: buildnum
        run: echo "BUILD_NUMBER=$(( $BUILD_NUMBER_OFFSET + $GITHUB_RUN_NUMBER ))" >> $GITHUB_ENV
        
      - name: Set combined tag
        run: echo "COMBINED_TAG=${BUILD_NUMBER}-${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Build Docker image with run number tag
        run: docker build -t $REGISTRY:${{ COMBINED_TAG }} .

      - name: Build Docker image with latest tag
        run: docker build -t $REGISTRY:latest .

      - name: Push Docker image with run number tag
        run: docker push $REGISTRY:${{ COMBINED_TAG }}

      - name: Push Docker image with latest tag
        run: docker push $REGISTRY:latest

      - name: Remove local images
        run: |
          docker rmi $REGISTRY:${{ COMBINED_TAG }} || true
          docker rmi $REGISTRY:latest || true
